CREATE TABLE "authors" (
  "author_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "is_committee" boolean
);

CREATE TABLE "papers" (
  "paper_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar
);

CREATE TABLE "paper_authors" (
  "paper_author_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paper_id" bigint,
  "author_id" bigint
);

CREATE TABLE "paper_reviews" (
  "paper_review_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paper_id" bigint,
  "author_id" bigint,
  "review" text,
  "rating" int
);

CREATE TABLE "statuses" (
  "status_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paper_id" bigint,
  "is_rejected" boolean
);

CREATE TABLE "keywords" (
  "keyword_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "paper_id" bigint,
  "keyword" varchar
);

ALTER TABLE "paper_authors" ADD FOREIGN KEY ("paper_id") REFERENCES "papers" ("paper_id");

ALTER TABLE "paper_authors" ADD FOREIGN KEY ("author_id") REFERENCES "authors" ("author_id");

ALTER TABLE "paper_reviews" ADD FOREIGN KEY ("paper_id") REFERENCES "papers" ("paper_id");

ALTER TABLE "paper_reviews" ADD FOREIGN KEY ("author_id") REFERENCES "authors" ("author_id");

ALTER TABLE "statuses" ADD FOREIGN KEY ("paper_id") REFERENCES "papers" ("paper_id");

ALTER TABLE "keywords" ADD FOREIGN KEY ("paper_id") REFERENCES "papers" ("paper_id");
